---
Name: sidebar
---
Page:
  extensions:
    - SidebarPageExtension
Page_Controller:
  extensions:
    - SidebarPageControllerExtension
SiteConfig:
  extensions:
    - SidebareSiteConfigExtension
---
Only:
  moduleexists: 'fluent'
---
SidebarWidget:
  extensions:
    - FluentExtension